spring:  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  datasource:
    generate-unique-name: false
    driver-class-name: org.postgresql.Driver

    # ----------------- LocalHost DB --------------------
    url: jdbc:postgresql://172.17.0.2:5432/dev2
    username: postgres
    password: admin

    # ----------------- Dev Environment DB --------------------
    

    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 10000
      pool-name: saadhakPool
      max-lifetime: 2000000
      connection-timeout: 30000
      leak-detection-threshold: 0

eureka:
  client:
  #  fetch-registry: false
  #  register-with-eureka: false
    service-url:
      defaultZone: http://172.17.0.2:8761/eureka/
  #server:
  #  wait-time-in-ms-when-sync-empty: 0

#Custom properties
token:
  key: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"

application:
  application-url: https://dev.teqnalyze.com
  application-reset-url: ${application.url}/reset-new-password

server:
  port: 8001
