spring:
  cloud:
    gateway:
      routes:
        - id: saadhak-app-users-1
          uri:
            lb://SAADHAK-APP-USERS
          predicates:
            - Path=/api/v1/users/status/check


server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://192.168.29.244:8761/eureka/




